# Generated by Django 4.2.2 on 2023-12-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog_db",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=100)),
                ("date", models.DateField(max_length=100)),
                ("title", models.CharField(max_length=50)),
                ("excerpt", models.CharField(max_length=200)),
                ("content", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, default="")),
            ],
        ),
    ]
