# Generated by Django 4.2.2 on 2023-12-07 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog_db",
            options={"verbose_name_plural": "Blog Entries"},
        ),
    ]
