# Generated by Django 4.2.2 on 2023-12-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_author_alter_blog_db_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name_plural": "Author Entries"},
        ),
        migrations.AddField(
            model_name="blog_db",
            name="blog_tags",
            field=models.ManyToManyField(to="blog.tag"),
        ),
    ]
